export const samplePaymentRules = [
  {
    paymentPlan: '全盈+PAY玉山',
    paymentTool: '全盈+PAY',
    paymentType: 'paypay',
    enabled: true,
    effectiveRewardRate: 0.185,
    minSpendTwd: 0,
    singleLimitTwd: 769,
    cumulativeLimitTwd: 769,
    description: '回饋高，但需注意額滿與上限',
  },
  {
    paymentPlan: '全盈+PAY國泰',
    paymentTool: '全盈+PAY',
    paymentType: 'paypay',
    enabled: true,
    effectiveRewardRate: 0.115,
    minSpendTwd: 0,
    singleLimitTwd: 1333,
    cumulativeLimitTwd: 5000,
    description: '適合一般消費補位',
  },
  {
    paymentPlan: 'Suica',
    paymentTool: 'Suica',
    paymentType: 'suica',
    enabled: true,
    effectiveRewardRate: 0.0672,
    minSpendTwd: 0,
    singleLimitTwd: null,
    cumulativeLimitTwd: null,
    description: '交通與支援 Suica 的小額付款',
  },
  {
    paymentPlan: 'J卡',
    paymentTool: '信用卡',
    paymentType: 'card',
    enabled: true,
    effectiveRewardRate: 0.045,
    minSpendTwd: 1000,
    singleLimitTwd: null,
    cumulativeLimitTwd: 33333,
    description: '未滿 1000 台幣不建議使用',
  },
  {
    paymentPlan: '日幣現金',
    paymentTool: '現金',
    paymentType: 'cash',
    enabled: true,
    effectiveRewardRate: 0,
    minSpendTwd: 0,
    singleLimitTwd: null,
    cumulativeLimitTwd: null,
    description: '作為兜底支付方式',
  },
];

export const sampleShoppingRecords = [
  {
    date: '2026-04-21',
    location: '札幌',
    store: 'LAWSON',
    category: '食物',
    name: '早餐',
    quantity: 1,
    total: 540,
    jpyNet: 500,
    tax: '10%',
    jpyAmount: 540,
    twdAmount: 118,
    fee: 2,
    twdTotal: 120,
    payment: 'Suica',
    rate: 0.2222,
  },
  {
    date: '2026-04-21',
    location: '札幌',
    store: '札幌藥妝',
    category: '生活用品',
    name: '藥妝補貨',
    quantity: 1,
    total: 4800,
    jpyNet: 4364,
    tax: '10%',
    jpyAmount: 4800,
    twdAmount: 1040,
    fee: 18,
    twdTotal: 1058,
    payment: '全盈+PAY玉山',
    rate: 0.2167,
  },
];

export const sampleSuicaRecords = [
  {
    date: '2026-04-20',
    chargeJpy: 3000,
    chargeTwd: 660,
    actualRate: 0.22,
    rewardRate: 0.045,
    rewardAmount: 30,
    actualCostTwd: 630,
    usedJpy: 540,
    remainingJpy: 2460,
    status: '已出帳',
    note: 'J卡儲值',
  },
];
